= TigerGraph GraphQL Service
:page-aliases: intro.adoc

TigerGraph GraphQL Service enables users to access and modify graph data in TigerGraph using GraphQL queries.
With TigerGraph GraphQL Service, you can use any GraphQL client or simply submit GraphQL queries directly to the service to access the graph data in TigerGraph.

Already familiar with GraphQL? Skip ahead to the xref:getting-started.adoc[] or first get to know GraphQL below.

== Get to Know GraphQL
[.home-card,cols="2",grid=none,frame=none]
|===
a|
*Schema*

Learn how TigerGraph GraphQL Service translates TigerGraph’s GSQL schema into a GraphQL
xref:schema.adoc[].

a|
*Queries*

Learn how to create GraphQL xref:queries.adoc[] to fetch specific fields of vertices and edges in a graph.

a|
*Filtering*

Learn how GraphQL service supports xref:filtering.adoc[] of query outputs.

a|
*Sorting*

Learn how GraphQL can xref:sorting.adoc[sort] the results of a query.

a|
*Pagination*

Learn how to limit the number of results you want returned from a query with
xref:pagination.adoc[].

a|
*Mutation*

Learn how GraphQL uses xref:mutation.adoc[] to insert and delete vertices and edges.
a|
|===




