= TigerGraph GraphQL Service
:page-aliases: intro.adoc

TigerGraph GraphQL Service enables users to access and modify graph data in TigerGraph using GraphQL queries.
With TigerGraph GraphQL Service, you can use any GraphQL client or simply submit GraphQL queries directly to the service to access the graph data in TigerGraph.

Our documentation includes a quickstart guide to help you get started with TigerGraph GraphQL Service, as well as guides on how to write GraphQL queries to access, filter, sort, and modify graph data.
Use the following links to get started:

* xref:getting-started.adoc[]

Already familiar with GSQL? Skip ahead to What sets GSQL apart to learn more about the language design, or first get to know GSQL below.


== Get to Know GraphQL
[.home-card,cols="2",grid=none,frame=none]
|===
a|
*Schema*

* xref:schema.adoc[]

a|
*Queries*

* xref:queries.adoc[]

a|
*Filtering*

* xref:filtering.adoc[]

a|
*Sorting*

* xref:sorting.adoc[]

a|
*Pagination*

* xref:pagination.adoc[]

a|
*Mutation*

* xref:mutation.adoc[]
a|
|===




