= TigerGraph GraphQL Service
:page-aliases: index.adoc

TigerGraph GraphQL Service enables users to access graph data in TigerGraph using GraphQL queries.
With TigerGraph GraphQL Service, you will be able to use any GraphQL client or to simply submit GraphQL queries directly to the service to quickly access the graph data in TigerGraph.
In the near future the service will also support data update operations via GraphQL mutations.

NOTE: TigerGraph GraphQL Service works with TigerGraph versions 3.0 and above.

Our documentation includes a quickstart guide to help you get started with TigerGraph GraphQL Service, as well as guides on how to write GraphQL queries to access, filter, and sort graph data.
Use the links below to get started:

* xref:getting-started.adoc[]
* xref:authentication.adoc[]
* xref:schema.adoc[]
* xref:queries.adoc[]
* xref:filtering.adoc[]
* xref:sorting.adoc[]
* xref:pagination.adoc[]

== Release note
TigerGraph GraphQL service was released on Feb 7th, 2022.
Here is a list of features added in this release:

* Added support for link:https://graphql.org/learn/queries/#variables[parameterized queries].
* Added support for link:https://graphql.org/learn/queries/#fragments[GraphQL fragments].
* Support for `order-by` and `limit` on fields that represent outgoing edges from vertices
* Added support for link:https://graphql.org/learn/queries/#aliases[GraphQL aliases].




